services:
  app:
    build:
      context: ./docker/php
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
    container_name: ochoa2_app
    restart: unless-stopped
    mem_limit: 900m
    volumes:
      - ./src:/var/www/html:z
    env_file:
      - .env.prod
    networks:
      - ochoa2_network
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: ochoa2_web
    restart: unless-stopped
    mem_limit: 100m
    volumes:
      - ./src:/var/www/html:z
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,z
    networks:
      - ochoa2_network
      - proxy
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: ochoa2_db
    restart: unless-stopped
    mem_limit: 700m
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ochoa2_network
    command:
      - --innodb-buffer-pool-size=192M
      - --performance-schema=OFF
      - --max-connections=50

networks:
  ochoa2_network:
    driver: bridge
  proxy:
    external: true

volumes:
  dbdata:
